export const UI_TEXTS = {
  title: 'Star Wars Game',
  drawCardsButton: 'Draw cards',
  people: 'People',
  starships: 'Starships',
  cardA: 'Card A',
  cardB: 'Card B',
  peopleTemplate: {
    birthYear: 'Birth year',
    gender: 'Gender',
    height: 'Height',
    mass: 'Mass',
    hairColor: 'Hair color',
    skinColor: 'Skin color',
    eyeColor: 'Eye color',
  },
  starshipTemplate: {
    model: 'Model',
    manufacturer: 'Manufacturer',
    costInCredits: 'Cost in credits',
    length: 'Length',
    maxSpeed: 'Max speed',
    crew: 'Crew',
    passengers: 'Passengers',
    cargoCapacity: 'Cargo capacity',
    consumables: 'Consumables',
    hyperdriveRating: 'Hyperdrive rating',
    starshipClass: 'Starship class',
  },
};
